// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.0
// source: pb/person/person.proto

package person

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	home "pb_test/pb/home"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Person_SEX int32

const (
	Person_MAN   Person_SEX = 0
	Person_WOMAN Person_SEX = 1
	Person_GIRL  Person_SEX = 1
	Person_OTHER Person_SEX = 2
)

// Enum value maps for Person_SEX.
var (
	Person_SEX_name = map[int32]string{
		0: "MAN",
		1: "WOMAN",
		// Duplicate value: 1: "GIRL",
		2: "OTHER",
	}
	Person_SEX_value = map[string]int32{
		"MAN":   0,
		"WOMAN": 1,
		"GIRL":  1,
		"OTHER": 2,
	}
)

func (x Person_SEX) Enum() *Person_SEX {
	p := new(Person_SEX)
	*p = x
	return p
}

func (x Person_SEX) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Person_SEX) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_person_person_proto_enumTypes[0].Descriptor()
}

func (Person_SEX) Type() protoreflect.EnumType {
	return &file_pb_person_person_proto_enumTypes[0]
}

func (x Person_SEX) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Person_SEX.Descriptor instead.
func (Person_SEX) EnumDescriptor() ([]byte, []int) {
	return file_pb_person_person_proto_rawDescGZIP(), []int{1, 0}
}

type Home struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Persons []*Person `protobuf:"bytes,1,rep,name=persons,proto3" json:"persons,omitempty"` // 嵌套
	V       *Home_V   `protobuf:"bytes,2,opt,name=v,proto3" json:"v,omitempty"`
}

func (x *Home) Reset() {
	*x = Home{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_person_person_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Home) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Home) ProtoMessage() {}

func (x *Home) ProtoReflect() protoreflect.Message {
	mi := &file_pb_person_person_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Home.ProtoReflect.Descriptor instead.
func (*Home) Descriptor() ([]byte, []int) {
	return file_pb_person_person_proto_rawDescGZIP(), []int{0}
}

func (x *Home) GetPersons() []*Person {
	if x != nil {
		return x.Persons
	}
	return nil
}

func (x *Home) GetV() *Home_V {
	if x != nil {
		return x.V
	}
	return nil
}

type Person struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age  int32      `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	Sex  Person_SEX `protobuf:"varint,3,opt,name=sex,proto3,enum=person.Person_SEX" json:"sex,omitempty"` // 枚举类型
	Test []string   `protobuf:"bytes,4,rep,name=test,proto3" json:"test,omitempty"`                       // 数组
	// Types that are assignable to TestOneOf:
	//	*Person_One
	//	*Person_Two
	//	*Person_Three
	TestOneOf isPerson_TestOneOf `protobuf_oneof:"TestOneOf"`
	Home      *home.Home         `protobuf:"bytes,9,opt,name=home,proto3" json:"home,omitempty"` // 外部引用
}

func (x *Person) Reset() {
	*x = Person{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_person_person_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Person) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Person) ProtoMessage() {}

func (x *Person) ProtoReflect() protoreflect.Message {
	mi := &file_pb_person_person_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Person.ProtoReflect.Descriptor instead.
func (*Person) Descriptor() ([]byte, []int) {
	return file_pb_person_person_proto_rawDescGZIP(), []int{1}
}

func (x *Person) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Person) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *Person) GetSex() Person_SEX {
	if x != nil {
		return x.Sex
	}
	return Person_MAN
}

func (x *Person) GetTest() []string {
	if x != nil {
		return x.Test
	}
	return nil
}

func (m *Person) GetTestOneOf() isPerson_TestOneOf {
	if m != nil {
		return m.TestOneOf
	}
	return nil
}

func (x *Person) GetOne() string {
	if x, ok := x.GetTestOneOf().(*Person_One); ok {
		return x.One
	}
	return ""
}

func (x *Person) GetTwo() string {
	if x, ok := x.GetTestOneOf().(*Person_Two); ok {
		return x.Two
	}
	return ""
}

func (x *Person) GetThree() string {
	if x, ok := x.GetTestOneOf().(*Person_Three); ok {
		return x.Three
	}
	return ""
}

func (x *Person) GetHome() *home.Home {
	if x != nil {
		return x.Home
	}
	return nil
}

type isPerson_TestOneOf interface {
	isPerson_TestOneOf()
}

type Person_One struct {
	One string `protobuf:"bytes,6,opt,name=one,proto3,oneof"`
}

type Person_Two struct {
	Two string `protobuf:"bytes,7,opt,name=two,proto3,oneof"`
}

type Person_Three struct {
	Three string `protobuf:"bytes,8,opt,name=three,proto3,oneof"`
}

func (*Person_One) isPerson_TestOneOf() {}

func (*Person_Two) isPerson_TestOneOf() {}

func (*Person_Three) isPerson_TestOneOf() {}

type Home_V struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Home_V) Reset() {
	*x = Home_V{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_person_person_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Home_V) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Home_V) ProtoMessage() {}

func (x *Home_V) ProtoReflect() protoreflect.Message {
	mi := &file_pb_person_person_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Home_V.ProtoReflect.Descriptor instead.
func (*Home_V) Descriptor() ([]byte, []int) {
	return file_pb_person_person_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Home_V) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_pb_person_person_proto protoreflect.FileDescriptor

var file_pb_person_person_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x62, 0x2f, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x2f, 0x70, 0x65, 0x72, 0x73,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e,
	0x1a, 0x12, 0x70, 0x62, 0x2f, 0x68, 0x6f, 0x6d, 0x65, 0x2f, 0x68, 0x6f, 0x6d, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x67, 0x0a, 0x04, 0x48, 0x6f, 0x6d, 0x65, 0x12, 0x28, 0x0a, 0x07,
	0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x2e, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x52, 0x07, 0x70,
	0x65, 0x72, 0x73, 0x6f, 0x6e, 0x73, 0x12, 0x1c, 0x0a, 0x01, 0x76, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x2e, 0x48, 0x6f, 0x6d, 0x65, 0x2e,
	0x56, 0x52, 0x01, 0x76, 0x1a, 0x17, 0x0a, 0x01, 0x56, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x99, 0x02,
	0x0a, 0x06, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x61, 0x67, 0x65, 0x12, 0x24,
	0x0a, 0x03, 0x73, 0x65, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x70, 0x65,
	0x72, 0x73, 0x6f, 0x6e, 0x2e, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x2e, 0x53, 0x45, 0x58, 0x52,
	0x03, 0x73, 0x65, 0x78, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x73, 0x74, 0x18, 0x04, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x03, 0x6f, 0x6e, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x03, 0x6f, 0x6e, 0x65, 0x12, 0x12, 0x0a, 0x03,
	0x74, 0x77, 0x6f, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x03, 0x74, 0x77, 0x6f,
	0x12, 0x16, 0x0a, 0x05, 0x74, 0x68, 0x72, 0x65, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x05, 0x74, 0x68, 0x72, 0x65, 0x65, 0x12, 0x1e, 0x0a, 0x04, 0x68, 0x6f, 0x6d, 0x65,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x68, 0x6f, 0x6d, 0x65, 0x2e, 0x48, 0x6f,
	0x6d, 0x65, 0x52, 0x04, 0x68, 0x6f, 0x6d, 0x65, 0x22, 0x32, 0x0a, 0x03, 0x53, 0x45, 0x58, 0x12,
	0x07, 0x0a, 0x03, 0x4d, 0x41, 0x4e, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x57, 0x4f, 0x4d, 0x41,
	0x4e, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x47, 0x49, 0x52, 0x4c, 0x10, 0x01, 0x12, 0x09, 0x0a,
	0x05, 0x4f, 0x54, 0x48, 0x45, 0x52, 0x10, 0x02, 0x1a, 0x02, 0x10, 0x01, 0x42, 0x0b, 0x0a, 0x09,
	0x54, 0x65, 0x73, 0x74, 0x4f, 0x6e, 0x65, 0x4f, 0x66, 0x4a, 0x04, 0x08, 0x05, 0x10, 0x06, 0x52,
	0x08, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x6d, 0x61, 0x70, 0x32, 0xc6, 0x01, 0x0a, 0x0d, 0x53, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x28, 0x0a, 0x06, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x0e, 0x2e, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x2e, 0x50,
	0x65, 0x72, 0x73, 0x6f, 0x6e, 0x1a, 0x0e, 0x2e, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x2e, 0x50,
	0x65, 0x72, 0x73, 0x6f, 0x6e, 0x12, 0x2c, 0x0a, 0x08, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x49,
	0x6e, 0x12, 0x0e, 0x2e, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x2e, 0x50, 0x65, 0x72, 0x73, 0x6f,
	0x6e, 0x1a, 0x0e, 0x2e, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x2e, 0x50, 0x65, 0x72, 0x73, 0x6f,
	0x6e, 0x28, 0x01, 0x12, 0x2d, 0x0a, 0x09, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x4f, 0x75, 0x74,
	0x12, 0x0e, 0x2e, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x2e, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e,
	0x1a, 0x0e, 0x2e, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x2e, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e,
	0x30, 0x01, 0x12, 0x2e, 0x0a, 0x08, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x49, 0x4f, 0x12, 0x0e,
	0x2e, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x2e, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x1a, 0x0e,
	0x2e, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x2e, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x28, 0x01,
	0x30, 0x01, 0x42, 0x1a, 0x5a, 0x18, 0x70, 0x62, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x2f, 0x70, 0x62,
	0x2f, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x3b, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_person_person_proto_rawDescOnce sync.Once
	file_pb_person_person_proto_rawDescData = file_pb_person_person_proto_rawDesc
)

func file_pb_person_person_proto_rawDescGZIP() []byte {
	file_pb_person_person_proto_rawDescOnce.Do(func() {
		file_pb_person_person_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_person_person_proto_rawDescData)
	})
	return file_pb_person_person_proto_rawDescData
}

var file_pb_person_person_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pb_person_person_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pb_person_person_proto_goTypes = []interface{}{
	(Person_SEX)(0),   // 0: person.Person.SEX
	(*Home)(nil),      // 1: person.Home
	(*Person)(nil),    // 2: person.Person
	(*Home_V)(nil),    // 3: person.Home.V
	(*home.Home)(nil), // 4: home.Home
}
var file_pb_person_person_proto_depIdxs = []int32{
	2, // 0: person.Home.persons:type_name -> person.Person
	3, // 1: person.Home.v:type_name -> person.Home.V
	0, // 2: person.Person.sex:type_name -> person.Person.SEX
	4, // 3: person.Person.home:type_name -> home.Home
	2, // 4: person.SearchService.Search:input_type -> person.Person
	2, // 5: person.SearchService.SearchIn:input_type -> person.Person
	2, // 6: person.SearchService.SearchOut:input_type -> person.Person
	2, // 7: person.SearchService.SearchIO:input_type -> person.Person
	2, // 8: person.SearchService.Search:output_type -> person.Person
	2, // 9: person.SearchService.SearchIn:output_type -> person.Person
	2, // 10: person.SearchService.SearchOut:output_type -> person.Person
	2, // 11: person.SearchService.SearchIO:output_type -> person.Person
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pb_person_person_proto_init() }
func file_pb_person_person_proto_init() {
	if File_pb_person_person_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_person_person_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Home); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_person_person_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Person); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_person_person_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Home_V); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_pb_person_person_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*Person_One)(nil),
		(*Person_Two)(nil),
		(*Person_Three)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_person_person_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_person_person_proto_goTypes,
		DependencyIndexes: file_pb_person_person_proto_depIdxs,
		EnumInfos:         file_pb_person_person_proto_enumTypes,
		MessageInfos:      file_pb_person_person_proto_msgTypes,
	}.Build()
	File_pb_person_person_proto = out.File
	file_pb_person_person_proto_rawDesc = nil
	file_pb_person_person_proto_goTypes = nil
	file_pb_person_person_proto_depIdxs = nil
}
